### ISSUE TITLE
thumb service: ensure delayed job restarted  with cap deployment

### ISSUE THREAD

**Issue by aalsum** [sul-dlss/was-thumbnail-service#15]

**Comment by ndushay** [comment]
AFAICT, this is done and working so I am closing this.

**Comment by ndushay** [comment]
NOPE - it's still broken.

**Comment by ndushay** [comment]
It appears there has been a long standing error with the `run_thumbnail_monitor` code:

```
was@was-thumbnail-stage current]$ RAILS_ENV=production bundle exec rake was_thumbnail_service:run_thumbnail_monitor --silent
<snip>
rake aborted!
NoMethodError: undefined method `zero?' for #<Array:0x00000005c44d20>
/opt/app/was/was-thumbnail-service/releases/20170122055700/lib/was/thumbnail_service/picker/memento_picker_threshold_grouping.rb:9:in `choose_mementos'
/opt/app/was/was-thumbnail-service/releases/20170122055700/lib/was/thumbnail_service/picker/memento_picker.rb:27:in `choose_mementos'
/opt/app/was/was-thumbnail-service/releases/20170122055700/lib/was/thumbnail_service/picker/memento_picker.rb:12:in `pick_mementos'
/opt/app/was/was-thumbnail-service/releases/20170122055700/lib/was/thumbnail_service/generator.rb:15:in `run'
/opt/app/was/was-thumbnail-service/releases/20170122055700/lib/was/thumbnail_service/monitor.rb:17:in `block in run'
/opt/app/was/was-thumbnail-service/shared/bundle/ruby/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in `each'
/opt/app/was/was-thumbnail-service/shared/bundle/ruby/2.1.0/gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in `each'
/opt/app/was/was-thumbnail-service/releases/20170122055700/lib/was/thumbnail_service/monitor.rb:8:in `run'
/opt/app/was/was-thumbnail-service/releases/20170122055700/Rakefile:15:in `block (2 levels) in <top (required)>'
/opt/app/was/was-thumbnail-service/shared/bundle/ruby/2.1.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
Tasks: TOP => was_thumbnail_service:run_thumbnail_monitor
(See full trace by running task with --trace)
```

I have put a fix to this error in the `monitoring` branch I'm working in (to work on nagios checks).

**Comment by ndushay** [comment]
with the fix in, `run_thumbnail_monitor.log` is showing regular checks for new mementos from the cron job running every 30 min per `whenever` gem.

I *think* that means this ticket is done ...

**Comment by ndushay** [comment]
Leaving this open because I believe the deploy:restart does NOT kill the old delayed job process ... and shouldn't it?
