### ISSUE TITLE
thumb service PROD error:  No route matches [GET] "/api/v1/was/thumbnails/druid_id"

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/was-thumbnail-service#56]
This error occurs in production.  I'm not sure where it is coming from.  

Full error in logs:
```
I, [2017-01-22T00:53:39.453030 #31539]  INFO -- : Started GET "/api/v1/was/thumbnails/druid_id" for 171.67.21.37 at 2017-01-22 00:53:39 -0800
F, [2017-01-22T00:53:39.455954 #31539] FATAL -- : 
ActionController::RoutingError (No route matches [GET] "/api/v1/was/thumbnails/druid_id"):
  actionpack (4.2.7.1) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.7.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.7.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.7.1) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.7.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.7.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.7.1) lib/rails/application.rb:165:in `call'
  /usr/local/rvm/gems/ruby-2.1.4/gems/passenger-5.0.22/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
  /usr/local/rvm/gems/ruby-2.1.4/gems/passenger-5.0.22/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:152:in `accept_and_process_next_request'
  /usr/local/rvm/gems/ruby-2.1.4/gems/passenger-5.0.22/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
  /usr/local/rvm/gems/ruby-2.1.4/gems/passenger-5.0.22/src/ruby_supportlib/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
  /usr/local/rvm/gems/ruby-2.1.4/gems/passenger-5.0.22/src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
```

**Comment by ndushay** [comment]
These were coming from sul-embed's okcomputer `status/all`, which nagios was using.  See PR sul-dlss/sul-embed#735 for fix.  W00t!
